### PR TITLE
Change CI from Travis to GitHub Actions

### PR DESCRIPTION
**Pull request by phil-davis**
Add a first GitHub workflow CI. I expect that the PHP "extensions" list will need to be expanded. But I  think that I have to merge first, in order to get the first run. So there is likely to be a followup PR.

### CODE REVIEW

**Comment by phil-davis** [comment]
@staabm pleases remove Travis from the required CI status

**Comment by staabm** [comment]
@phil-davis done

**Comment by staabm** [comment]
@phil-davis after you are done with all the reposes, I can enforce succesfull github action in all sabre/ reposes en block

**Comment by phil-davis** [comment]
> @phil-davis after you are done with all the reposes, I can enforce succesfull github action in all sabre/ reposes en block

I will let you know.

I will do these in the coming hours:
- event
- skel (I may as well keep the "template" up-to-date there)
- uri
- xml-atom
- Baikal

@staabm please remove the required status for Travis on those.

**Comment by staabm** [comment]
@phil-davis done

**Pull request merged**
